#!/bin/bash

# Directus Setup Script
# This script creates a .env file with randomly generated secure values

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit

# Check if .env already exists
if [ -f .env ]; then
    echo "Warning: .env file already exists!"
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Generate random values
DIRECTUS_KEY=$(openssl rand -hex 32)
DIRECTUS_SECRET=$(openssl rand -hex 32)
DIRECTUS_DB_PASSWORD=$(openssl rand -hex 16)
DIRECTUS_ADMIN_PASSWORD=$(openssl rand -hex 16)

# Create .env file
cat > .env << EOF
# Directus Configuration
# Generated by setup.sh

# Directus Keys
DIRECTUS_KEY=${DIRECTUS_KEY}
DIRECTUS_SECRET=${DIRECTUS_SECRET}

# Database Configuration
DIRECTUS_DB_DATABASE=directus
DIRECTUS_DB_USER=directus
DIRECTUS_DB_PASSWORD=${DIRECTUS_DB_PASSWORD}

# Admin Credentials
DIRECTUS_ADMIN_EMAIL=admin@localhost
DIRECTUS_ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}

# Public URL
DIRECTUS_PUBLIC_URL=http://localhost:8055
EOF

# Set proper permissions
chmod 600 .env

echo "Directus .env file created successfully!"
echo ""
echo "Generated credentials:"
echo "  Admin Email: admin@localhost"
echo "  Admin Password: ${DIRECTUS_ADMIN_PASSWORD}"
echo ""
echo "To start Directus, run: ./start.sh"
echo ""
echo "IMPORTANT: Keep your .env file secure!"
echo "Do not commit it to version control."
